name: efashion_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  image_picker: ^1.0.4
  auto_route: ^7.8.3
  flutter_screenutil: ^5.9.0
  flutter_animate: ^4.2.0+1
  get_it: ^7.6.4
  injectable: ^2.3.0
  iconsax: ^0.0.8
  cached_network_image: ^3.2.3
  hive_flutter: ^1.1.0
  rxdart: ^0.27.7
  flutter_cache_manager: ^3.3.1
  hive: ^2.2.3
  carousel_slider: ^4.2.1
  bloc_concurrency: ^0.2.2
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  flutter_typeahead: ^4.6.2
  syncfusion_flutter_sliders: ^22.2.12
  syncfusion_flutter_core: ^22.2.12
  easy_stepper: ^0.7.3
  pinput: ^3.0.1
  dartz: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  auto_route_generator: ^7.3.1
  injectable_generator: ^2.4.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
 
flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
    - family: DM Serif Display
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
          weight: 400