// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAAjE7HWGqRgvGmFG5mnwYOaDunov5ii0',
    appId: '1:741865556047:web:910900f8a4a18a9009c23a',
    messagingSenderId: '741865556047',
    projectId: 'efash-391423',
    authDomain: 'efash-391423.firebaseapp.com',
    storageBucket: 'efash-391423.appspot.com',
    measurementId: 'G-52DEN4VG0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOz4KBLdsuwbkGPOthnOeaIc-ZfBexkk4',
    appId: '1:741865556047:android:14ed868c82a9c88a09c23a',
    messagingSenderId: '741865556047',
    projectId: 'efash-391423',
    storageBucket: 'efash-391423.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2qFsbopPBiZXkC9Wh_pStDB0yn_xr0wU',
    appId: '1:741865556047:ios:ce66bb8e1445dca109c23a',
    messagingSenderId: '741865556047',
    projectId: 'efash-391423',
    storageBucket: 'efash-391423.appspot.com',
    iosBundleId: 'com.example.efashionFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2qFsbopPBiZXkC9Wh_pStDB0yn_xr0wU',
    appId: '1:741865556047:ios:4f486a3c19e7097809c23a',
    messagingSenderId: '741865556047',
    projectId: 'efash-391423',
    storageBucket: 'efash-391423.appspot.com',
    iosBundleId: 'com.example.efashionFlutter.RunnerTests',
  );
}
